# This stores the questions and answers

questions_db : list[dict] = [
    # TENSES & VERBS
    {"question": "I {blank} to the park yesterday.", "answer": 1, "variants": ["go", "went", "gone", "going"], "is_correct": False},
    {"question": "She {blank} her breakfast right now.", "answer": 3, "variants": ["eat", "eats", "ate", "is eating"], "is_correct": False},
    {"question": "We {blank} never seen that movie before.", "answer": 0, "variants": ["have", "has", "did", "were"], "is_correct": False},
    {"question": "They {blank} football when it started to rain.", "answer": 2, "variants": ["play", "played", "were playing", "have played"], "is_correct": False},
    {"question": "He {blank} to call you later tonight.", "answer": 1, "variants": ["going", "will", "shall", "is"], "is_correct": False},
    {"question": "By next year, I {blank} my degree.", "answer": 2, "variants": ["finish", "finished", "will have finished", "am finishing"], "is_correct": False},
    {"question": "I {blank} English for three years now.", "answer": 3, "variants": ["study", "studied", "am studying", "have been studying"], "is_correct": False},
    {"question": "If it {blank} tomorrow, we will stay home.", "answer": 1, "variants": ["rain", "rains", "rained", "will rain"], "is_correct": False},
    {"question": "She {blank} speak three languages fluently.", "answer": 0, "variants": ["can", "could", "is", "must"], "is_correct": False},
    {"question": "You {blank} not smoke in the hospital.", "answer": 2, "variants": ["do", "have", "must", "can"], "is_correct": False},
    
    # ARTICLES & PREPOSITIONS
    {"question": "I saw {blank} amazing movie last night.", "answer": 1, "variants": ["a", "an", "the", "some"], "is_correct": False},
    {"question": "He lives {blank} London.", "answer": 2, "variants": ["at", "on", "in", "to"], "is_correct": False},
    {"question": "The keys are {blank} the kitchen counter.", "answer": 1, "variants": ["in", "on", "at", "between"], "is_correct": False},
    {"question": "We usually meet {blank} noon.", "answer": 2, "variants": ["in", "on", "at", "for"], "is_correct": False},
    {"question": "She is interested {blank} learning photography.", "answer": 0, "variants": ["in", "on", "at", "about"], "is_correct": False},
    {"question": "They went to the store {blank} foot.", "answer": 1, "variants": ["by", "on", "with", "in"], "is_correct": False},
    {"question": "I am proud {blank} your achievements.", "answer": 3, "variants": ["for", "with", "in", "of"], "is_correct": False},
    {"question": "Wait {blank} me at the bus stop.", "answer": 0, "variants": ["for", "to", "at", "with"], "is_correct": False},
    {"question": "The plane flies {blank} the clouds.", "answer": 2, "variants": ["on", "under", "above", "through"], "is_correct": False},
    {"question": "I am looking {blank} my lost wallet.", "answer": 1, "variants": ["at", "for", "after", "into"], "is_correct": False},

    # SPELLING & CONFUSING WORDS
    {"question": "It is {blank} late to change your mind.", "answer": 1, "variants": ["to", "too", "two", "tow"], "is_correct": False},
    {"question": "I hope you enjoy {blank} vacation.", "answer": 2, "variants": ["you", "you're", "your", "yours"], "is_correct": False},
    {"question": "The {blank} is very hot today.", "answer": 0, "variants": ["weather", "whether", "wether", "rather"], "is_correct": False},
    {"question": "They left {blank} bags at the station.", "answer": 3, "variants": ["there", "they're", "theirs", "their"], "is_correct": False},
    {"question": "Which word is spelled correctly?", "answer": 0, "variants": ["separate", "seperate", "separet", "seperat"], "is_correct": False},
    {"question": "The {blank} of the school is very kind.", "answer": 1, "variants": ["principle", "principal", "prinsepal", "prinsipal"], "is_correct": False},
    {"question": "Can you {blank} me some money?", "answer": 2, "variants": ["borrow", "loan", "lend", "keep"], "is_correct": False},
    {"question": "I need some {blank} on which car to buy.", "answer": 0, "variants": ["advice", "advise", "advises", "advicing"], "is_correct": False},
    {"question": "The medicine had a strange {blank} on me.", "answer": 1, "variants": ["affect", "effect", "effact", "affact"], "is_correct": False},
    {"question": "She is more {blank} than her sister.", "answer": 3, "variants": ["tall", "taller", "tallest", "intelligent"], "is_correct": False},
    
    # PHRASAL VERBS
    {"question": "Could you please {blank} the lights? It's too bright.", "answer": 1, "variants": ["turn on", "turn off", "turn up", "turn into"], "is_correct": False},
    {"question": "I need to {blank} this word in the dictionary.", "answer": 2, "variants": ["look at", "look after", "look up", "look for"], "is_correct": False},
    {"question": "Don't {blank}; I know you can finish the race!", "answer": 0, "variants": ["give up", "give in", "give out", "give away"], "is_correct": False},
    {"question": "The plane will {blank} in ten minutes.", "answer": 3, "variants": ["take in", "take up", "take on", "take off"], "is_correct": False},
    {"question": "We {blank} of milk, so I need to go to the store.", "answer": 1, "variants": ["ran into", "ran out", "ran over", "ran away"], "is_correct": False},
    {"question": "I {blank} an old friend at the mall today.", "answer": 0, "variants": ["ran into", "ran after", "ran for", "ran up"], "is_correct": False},
    {"question": "You should {blank} your coat before you leave.", "answer": 2, "variants": ["put out", "put up", "put on", "put off"], "is_correct": False},
    {"question": "The meeting was {blank} until next week.", "answer": 3, "variants": ["put on", "put in", "put away", "put off"], "is_correct": False},
    {"question": "He decided to {blank} a new hobby.", "answer": 1, "variants": ["take off", "take up", "take out", "take after"], "is_correct": False},
    {"question": "Can you {blank} the volume? I can't hear the news.", "answer": 0, "variants": ["turn up", "turn down", "turn over", "turn around"], "is_correct": False},

    # MODALS & AUXILIARIES
    {"question": "You {blank} brush your teeth twice a day.", "answer": 2, "variants": ["might", "would", "should", "could"], "is_correct": False},
    {"question": "I {blank} swim when I was only five years old.", "answer": 1, "variants": ["can", "could", "may", "might"], "is_correct": False},
    {"question": "It {blank} rain later, so bring an umbrella.", "answer": 3, "variants": ["must", "shall", "would", "might"], "is_correct": False},
    {"question": "You {blank} not park your car here.", "answer": 0, "variants": ["must", "should", "could", "will"], "is_correct": False},
    {"question": "Would you {blank} passing me the salt?", "answer": 2, "variants": ["like", "please", "mind", "want"], "is_correct": False},
    {"question": "I {blank} rather stay home than go out tonight.", "answer": 1, "variants": ["should", "would", "could", "had"], "is_correct": False},
    {"question": "He {blank} be at home; his car is in the driveway.", "answer": 0, "variants": ["must", "might", "can", "should"], "is_correct": False},
    {"question": "We {blank} to finish the project by Friday.", "answer": 3, "variants": ["must", "should", "can", "have"], "is_correct": False},
    {"question": "May I {blank} a suggestion?", "answer": 1, "variants": ["do", "make", "give", "tell"], "is_correct": False},
    {"question": "You {blank} better hurry or you'll miss the train.", "answer": 2, "variants": ["would", "should", "had", "must"], "is_correct": False},

    # ADJECTIVES & ADVERBS
    {"question": "This is the {blank} movie I have ever seen.", "answer": 3, "variants": ["good", "better", "bestest", "best"], "is_correct": False},
    {"question": "She speaks English very {blank}.", "answer": 2, "variants": ["good", "goodly", "well", "best"], "is_correct": False},
    {"question": "He is {blank} than his brother.", "answer": 0, "variants": ["taller", "tallest", "more tall", "as tall"], "is_correct": False},
    {"question": "The exam was {blank} easy.", "answer": 1, "variants": ["surprise", "surprisingly", "surprised", "surprising"], "is_correct": False},
    {"question": "I haven't felt this {blank} in a long time.", "answer": 2, "variants": ["happily", "happiness", "happy", "happier"], "is_correct": False},
    {"question": "The flower smells {blank}.", "answer": 0, "variants": ["sweet", "sweetly", "sweeter", "sweetness"], "is_correct": False},
    {"question": "He arrived {blank} than expected.", "answer": 1, "variants": ["early", "earlier", "earliest", "more early"], "is_correct": False},
    {"question": "That was a {blank} decision.", "answer": 3, "variants": ["wisely", "wisdom", "wiser", "wise"], "is_correct": False},
    {"question": "She works {blank} to support her family.", "answer": 0, "variants": ["hard", "hardly", "harder", "hardest"], "is_correct": False},
    {"question": "The team played {blank} during the final match.", "answer": 2, "variants": ["bad", "badly", "worse", "worst"], "is_correct": False},

    # CONJUNCTIONS & CONNECTORS
    {"question": "I was tired, {blank} I went to bed early.", "answer": 1, "variants": ["but", "so", "because", "yet"], "is_correct": False},
    {"question": "She studied hard {blank} she failed the exam.", "answer": 3, "variants": ["so", "because", "and", "although"], "is_correct": False},
    {"question": "I'll call you {blank} I arrive at the airport.", "answer": 0, "variants": ["when", "while", "during", "since"], "is_correct": False},
    {"question": "You can have {blank} tea or coffee.", "answer": 2, "variants": ["neither", "nor", "either", "and"], "is_correct": False},
    {"question": "He didn't go to work {blank} he was sick.", "answer": 1, "variants": ["so", "because", "but", "although"], "is_correct": False},
    {"question": "Wait here {blank} I come back.", "answer": 3, "variants": ["for", "since", "while", "until"], "is_correct": False},
    {"question": "I like both chocolate {blank} vanilla.", "answer": 0, "variants": ["and", "or", "but", "also"], "is_correct": False},
    {"question": "He is very rich, {blank} he is not happy.", "answer": 2, "variants": ["so", "because", "yet", "and"], "is_correct": False},
    {"question": "I'll go to the beach {blank} it rains.", "answer": 1, "variants": ["if", "unless", "when", "whether"], "is_correct": False},
    {"question": "We stayed inside {blank} the storm.", "answer": 3, "variants": ["while", "since", "until", "during"], "is_correct": False},

    # QUANTIFIERS & NOUNS
    {"question": "How {blank} sugar do you want in your coffee?", "answer": 0, "variants": ["much", "many", "few", "little"], "is_correct": False},
    {"question": "There are {blank} people in the room.", "answer": 1, "variants": ["much", "many", "little", "any"], "is_correct": False},
    {"question": "I have {blank} friends in this city.", "answer": 2, "variants": ["a little", "any", "a few", "much"], "is_correct": False},
    {"question": "Can I have {blank} water, please?", "answer": 3, "variants": ["any", "many", "few", "some"], "is_correct": False},
    {"question": "There isn't {blank} milk in the fridge.", "answer": 0, "variants": ["any", "some", "many", "few"], "is_correct": False},
    {"question": "She has {blank} patience for rude people.", "answer": 2, "variants": ["few", "many", "little", "any"], "is_correct": False},
    {"question": "The {blank} are playing in the garden.", "answer": 1, "variants": ["child", "children", "childs", "childrens"], "is_correct": False},
    {"question": "I need to buy some new {blank}.", "answer": 3, "variants": ["furniture", "furnitures", "piece of furniture", "clothes"], "is_correct": False},
    {"question": "The {blank} is very clean in the mountains.", "answer": 0, "variants": ["air", "airs", "airy", "aired"], "is_correct": False},
    {"question": "I have {blank} information about the event.", "answer": 2, "variants": ["a", "an", "some", "many"], "is_correct": False},

    # --- NEW ADDITIONS (200 QUESTIONS) ---

    # CONDITIONALS (20)
    {"question": "If I {blank} you, I would take that job.", "answer": 1, "variants": ["am", "were", "was", "will be"], "is_correct": False},
    {"question": "If they had arrived earlier, they {blank} the train.", "answer": 2, "variants": ["will catch", "would catch", "would have caught", "caught"], "is_correct": False},
    {"question": "Unless you {blank} hard, you won't pass the exam.", "answer": 0, "variants": ["study", "will study", "studied", "don't study"], "is_correct": False},
    {"question": "I will go to the party if I {blank} time.", "answer": 3, "variants": ["had", "will have", "would have", "have"], "is_correct": False},
    {"question": "If she {blank} about the meeting, she would have attended.", "answer": 1, "variants": ["knows", "had known", "knew", "has known"], "is_correct": False},
    {"question": "What {blank} you do if you won the lottery?", "answer": 2, "variants": ["will", "can", "would", "do"], "is_correct": False},
    {"question": "If water reaches 100 degrees, it {blank}.", "answer": 0, "variants": ["boils", "boiled", "is boiling", "will boil"], "is_correct": False},
    {"question": "I would have helped him if he {blank} me.", "answer": 2, "variants": ["asks", "would ask", "had asked", "asked"], "is_correct": False},
    {"question": "If it {blank} tonight, we can go skiing tomorrow.", "answer": 3, "variants": ["snowed", "will snow", "would snow", "snows"], "is_correct": False},
    {"question": "Supposing you {blank} lost, what would you do?", "answer": 1, "variants": ["get", "got", "will get", "are getting"], "is_correct": False},
    {"question": "Provided that the weather {blank} good, we'll go for a hike.", "answer": 0, "variants": ["is", "was", "will be", "be"], "is_correct": False},
    {"question": "I wouldn't be here if you {blank} me.", "answer": 2, "variants": ["don't invite", "didn't invite", "hadn't invited", "not invited"], "is_correct": False},
    {"question": "If I {blank} more money, I would travel more.", "answer": 1, "variants": ["have", "had", "will have", "would have"], "is_correct": False},
    {"question": "She will be angry if you {blank} her birthday.", "answer": 3, "variants": ["forgot", "would forget", "will forget", "forget"], "is_correct": False},
    {"question": "If he {blank} so much, he wouldn't be so tired.", "answer": 1, "variants": ["doesn't work", "didn't work", "hasn't worked", "not work"], "is_correct": False},
    {"question": "Had I known you were coming, I {blank} a cake.", "answer": 2, "variants": ["baked", "would bake", "would have baked", "will bake"], "is_correct": False},
    {"question": "As long as you {blank} me, I will be happy.", "answer": 0, "variants": ["love", "will love", "loved", "loving"], "is_correct": False},
    {"question": "If I {blank} wings, I would fly to the moon.", "answer": 1, "variants": ["have", "had", "will have", "am having"], "is_correct": False},
    {"question": "But for your help, I {blank} failed.", "answer": 2, "variants": ["will", "would", "would have", "had"], "is_correct": False},
    {"question": "If you {blank} red and blue, you get purple.", "answer": 3, "variants": ["mixed", "will mix", "would mix", "mix"], "is_correct": False},

    # PASSIVE VOICE (20)
    {"question": "The bridge {blank} in 1920.", "answer": 1, "variants": ["built", "was built", "is built", "was building"], "is_correct": False},
    {"question": "English {blank} all over the world.", "answer": 2, "variants": ["speaks", "is speaking", "is spoken", "has spoken"], "is_correct": False},
    {"question": "A new hospital {blank} in our city right now.", "answer": 3, "variants": ["is building", "builds", "was built", "is being built"], "is_correct": False},
    {"question": "The letters {blank} by the postman every morning.", "answer": 0, "variants": ["are delivered", "delivered", "is delivered", "were delivered"], "is_correct": False},
    {"question": "The window {blank} by the wind last night.", "answer": 1, "variants": ["broke", "was broken", "is broken", "had broken"], "is_correct": False},
    {"question": "My car {blank} at the moment.", "answer": 2, "variants": ["is repairing", "repairs", "is being repaired", "repaired"], "is_correct": False},
    {"question": "The thief {blank} by the police yesterday.", "answer": 3, "variants": ["catches", "caught", "is caught", "was caught"], "is_correct": False},
    {"question": "Dinner {blank} when we arrived home.", "answer": 1, "variants": ["served", "was being served", "is served", "is serving"], "is_correct": False},
    {"question": "This book {blank} into many languages.", "answer": 2, "variants": ["has translated", "translated", "has been translated", "is translating"], "is_correct": False},
    {"question": "A decision {blank} by the end of the meeting.", "answer": 0, "variants": ["will be made", "will make", "is made", "made"], "is_correct": False},
    {"question": "The flowers {blank} by the gardener tomorrow.", "answer": 3, "variants": ["watered", "are watering", "will water", "will be watered"], "is_correct": False},
    {"question": "The homework {blank} by the students yet.", "answer": 1, "variants": ["didn't finish", "hasn't been finished", "hasn't finished", "isn't finishing"], "is_correct": False},
    {"question": "The room {blank} every day.", "answer": 0, "variants": ["is cleaned", "cleans", "is cleaning", "cleaned"], "is_correct": False},
    {"question": "He {blank} to the party, but he didn't come.", "answer": 2, "variants": ["invited", "invites", "was invited", "had invited"], "is_correct": False},
    {"question": "Rice {blank} in China for thousands of years.", "answer": 1, "variants": ["grown", "has been grown", "is growing", "grows"], "is_correct": False},
    {"question": "The cake {blank} into eight pieces.", "answer": 0, "variants": ["was cut", "cut", "is cutting", "cuts"], "is_correct": False},
    {"question": "The suspects {blank} by the detective right now.", "answer": 3, "variants": ["interrogated", "are interrogating", "interrogate", "are being interrogated"], "is_correct": False},
    {"question": "The song {blank} by a famous singer in 1980.", "answer": 1, "variants": ["wrote", "was written", "is written", "was writing"], "is_correct": False},
    {"question": "Tobacco {blank} in this area anymore.", "answer": 2, "variants": ["not grows", "doesn't grow", "isn't grown", "not grown"], "is_correct": False},
    {"question": "A lot of mistakes {blank} in the report.", "answer": 0, "variants": ["were made", "made", "was made", "were making"], "is_correct": False},

    # RELATIVE CLAUSES (20)
    {"question": "The man {blank} lives next door is a doctor.", "answer": 0, "variants": ["who", "which", "whom", "whose"], "is_correct": False},
    {"question": "This is the book {blank} I told you about.", "answer": 1, "variants": ["who", "that", "whom", "whose"], "is_correct": False},
    {"question": "That is the girl {blank} father is a pilot.", "answer": 3, "variants": ["who", "which", "whom", "whose"], "is_correct": False},
    {"question": "The restaurant {blank} we ate dinner was expensive.", "answer": 2, "variants": ["which", "that", "where", "whose"], "is_correct": False},
    {"question": "I remember the day {blank} we first met.", "answer": 0, "variants": ["when", "which", "where", "who"], "is_correct": False},
    {"question": "The car {blank} was stolen has been found.", "answer": 1, "variants": ["who", "which", "whom", "whose"], "is_correct": False},
    {"question": "The woman {blank} I saw at the park is my teacher.", "answer": 2, "variants": ["who", "which", "whom", "whose"], "is_correct": False},
    {"question": "He is the boy {blank} broke the window.", "answer": 0, "variants": ["who", "which", "that", "whose"], "is_correct": False},
    {"question": "The house {blank} roof is red is mine.", "answer": 3, "variants": ["who", "which", "that", "whose"], "is_correct": False},
    {"question": "This is the school {blank} I used to go.", "answer": 2, "variants": ["which", "that", "where", "when"], "is_correct": False},
    {"question": "I don't know the reason {blank} he left.", "answer": 0, "variants": ["why", "when", "where", "which"], "is_correct": False},
    {"question": "The people {blank} work here are very friendly.", "answer": 1, "variants": ["which", "who", "whom", "whose"], "is_correct": False},
    {"question": "Is this the movie {blank} won the Oscar?", "answer": 2, "variants": ["who", "whom", "that", "whose"], "is_correct": False},
    {"question": "The scientist {blank} discovered this is famous.", "answer": 0, "variants": ["who", "which", "whose", "whom"], "is_correct": False},
    {"question": "The town {blank} I grew up is very small.", "answer": 3, "variants": ["which", "that", "when", "where"], "is_correct": False},
    {"question": "The keys {blank} I lost were on the table.", "answer": 1, "variants": ["who", "that", "whom", "whose"], "is_correct": False},
    {"question": "A widow is a woman {blank} husband is dead.", "answer": 3, "variants": ["who", "which", "whom", "whose"], "is_correct": False},
    {"question": "Do you know the girl {blank} he is talking to?", "answer": 2, "variants": ["who", "which", "whom", "whose"], "is_correct": False},
    {"question": "The cake {blank} my mother made was delicious.", "answer": 1, "variants": ["who", "which", "whom", "whose"], "is_correct": False},
    {"question": "Spring is the season {blank} flowers bloom.", "answer": 0, "variants": ["when", "where", "which", "that"], "is_correct": False},

    # GERUNDS & INFINITIVES (20)
    {"question": "I enjoy {blank} books in my free time.", "answer": 1, "variants": ["to read", "reading", "read", "to reading"], "is_correct": False},
    {"question": "She decided {blank} a new car.", "answer": 0, "variants": ["to buy", "buying", "buy", "to buying"], "is_correct": False},
    {"question": "We plan {blank} on vacation next month.", "answer": 2, "variants": ["go", "going", "to go", "to going"], "is_correct": False},
    {"question": "Stop {blank} so much noise!", "answer": 3, "variants": ["to make", "make", "to making", "making"], "is_correct": False},
    {"question": "He offered {blank} me with my homework.", "answer": 0, "variants": ["to help", "helping", "help", "to helping"], "is_correct": False},
    {"question": "I finished {blank} my project last night.", "answer": 1, "variants": ["to do", "doing", "do", "to doing"], "is_correct": False},
    {"question": "Don't forget {blank} the lights.", "answer": 2, "variants": ["turn off", "turning off", "to turn off", "turn offing"], "is_correct": False},
    {"question": "I remember {blank} that person before.", "answer": 3, "variants": ["to see", "see", "to seeing", "seeing"], "is_correct": False},
    {"question": "They want {blank} to the cinema tonight.", "answer": 0, "variants": ["to go", "going", "go", "to going"], "is_correct": False},
    {"question": "He is good at {blank} football.", "answer": 1, "variants": ["to play", "playing", "play", "to playing"], "is_correct": False},
    {"question": "I'm looking forward to {blank} you.", "answer": 3, "variants": ["see", "to see", "saw", "seeing"], "is_correct": False},
    {"question": "It's no use {blank} about the past.", "answer": 1, "variants": ["to cry", "crying", "cry", "cried"], "is_correct": False},
    {"question": "She is interested in {blank} photography.", "answer": 2, "variants": ["to learn", "learn", "learning", "learned"], "is_correct": False},
    {"question": "I would like {blank} a cup of coffee.", "answer": 0, "variants": ["to have", "having", "have", "had"], "is_correct": False},
    {"question": "We agreed {blank} a break.", "answer": 2, "variants": ["taking", "take", "to take", "took"], "is_correct": False},
    {"question": "I avoid {blank} late at night.", "answer": 1, "variants": ["to work", "working", "work", "worked"], "is_correct": False},
    {"question": "He promised {blank} me back soon.", "answer": 0, "variants": ["to call", "calling", "call", "called"], "is_correct": False},
    {"question": "It started {blank} an hour ago.", "answer": 3, "variants": ["rain", "to raining", "rained", "raining"], "is_correct": False},
    {"question": "Would you mind {blank} the door?", "answer": 1, "variants": ["to open", "opening", "open", "opened"], "is_correct": False},
    {"question": "I can't stand {blank} in long queues.", "answer": 2, "variants": ["to wait", "wait", "waiting", "waited"], "is_correct": False},

    # SUBJECT-VERB AGREEMENT (20)
    {"question": "Either my parents or my brother {blank} coming.", "answer": 1, "variants": ["are", "is", "were", "be"], "is_correct": False},
    {"question": "The news {blank} very depressing today.", "answer": 2, "variants": ["are", "were", "is", "be"], "is_correct": False},
    {"question": "Politics {blank} a complicated subject.", "answer": 0, "variants": ["is", "are", "were", "be"], "is_correct": False},
    {"question": "Everyone {blank} to be happy.", "answer": 1, "variants": ["want", "wants", "is wanting", "are wanting"], "is_correct": False},
    {"question": "Ten dollars {blank} too much for this coffee.", "answer": 2, "variants": ["are", "were", "is", "be"], "is_correct": False},
    {"question": "Physics {blank} my favorite subject in school.", "answer": 0, "variants": ["was", "were", "are", "be"], "is_correct": False},
    {"question": "Each of the students {blank} a book.", "answer": 1, "variants": ["have", "has", "are having", "were having"], "is_correct": False},
    {"question": "The team {blank} playing well lately.", "answer": 3, "variants": ["are", "were", "be", "is"], "is_correct": False},
    {"question": "Bread and butter {blank} my daily breakfast.", "answer": 0, "variants": ["is", "are", "were", "be"], "is_correct": False},
    {"question": "Neither of the two candidates {blank} qualified.", "answer": 1, "variants": ["are", "is", "were", "be"], "is_correct": False},
    {"question": "The children {blank} playing in the park.", "answer": 0, "variants": ["are", "is", "was", "be"], "is_correct": False},
    {"question": "A lot of people {blank} here already.", "answer": 2, "variants": ["is", "was", "are", "be"], "is_correct": False},
    {"question": "Measles {blank} a dangerous disease.", "answer": 0, "variants": ["is", "are", "were", "be"], "is_correct": False},
    {"question": "One of my friends {blank} living in Tokyo.", "answer": 1, "variants": ["are", "is", "were", "be"], "is_correct": False},
    {"question": "There {blank} many books on the shelf.", "answer": 2, "variants": ["is", "was", "are", "be"], "is_correct": False},
    {"question": "The number of students {blank} increasing.", "answer": 1, "variants": ["are", "is", "were", "be"], "is_correct": False},
    {"question": "The scissors {blank} on the table.", "answer": 0, "variants": ["are", "is", "was", "be"], "is_correct": False},
    {"question": "Nobody {blank} where he is.", "answer": 1, "variants": ["know", "knows", "is knowing", "are knowing"], "is_correct": False},
    {"question": "My family {blank} very supportive.", "answer": 3, "variants": ["are", "were", "be", "is"], "is_correct": False},
    {"question": "Statistics {blank} a difficult course.", "answer": 0, "variants": ["is", "are", "were", "be"], "is_correct": False},

    # REPORTED SPEECH (20)
    {"question": "He said that he {blank} hungry.", "answer": 1, "variants": ["is", "was", "will be", "be"], "is_correct": False},
    {"question": "She told me she {blank} to London the next day.", "answer": 2, "variants": ["is going", "went", "was going", "goes"], "is_correct": False},
    {"question": "They asked me where I {blank}.", "answer": 0, "variants": ["lived", "live", "am living", "will live"], "is_correct": False},
    {"question": "He said he {blank} his homework already.", "answer": 3, "variants": ["does", "is doing", "has done", "had done"], "is_correct": False},
    {"question": "She asked if I {blank} swim.", "answer": 1, "variants": ["can", "could", "may", "might"], "is_correct": False},
    {"question": "He told me not {blank} any noise.", "answer": 2, "variants": ["make", "making", "to make", "made"], "is_correct": False},
    {"question": "She asked what time the train {blank}.", "answer": 0, "variants": ["left", "leaves", "is leaving", "will leave"], "is_correct": False},
    {"question": "They said they {blank} for two hours.", "answer": 3, "variants": ["wait", "are waiting", "have waited", "had been waiting"], "is_correct": False},
    {"question": "He asked her if she {blank} him.", "answer": 1, "variants": ["loves", "loved", "will love", "love"], "is_correct": False},
    {"question": "She said she {blank} call me later.", "answer": 2, "variants": ["will", "can", "would", "shall"], "is_correct": False},
    {"question": "They told us {blank} quiet.", "answer": 0, "variants": ["to be", "being", "be", "was"], "is_correct": False},
    {"question": "He said he {blank} never been to Paris.", "answer": 3, "variants": ["has", "is", "was", "had"], "is_correct": False},
    {"question": "She asked me why I {blank} crying.", "answer": 1, "variants": ["am", "was", "were", "be"], "is_correct": False},
    {"question": "He asked where the post office {blank}.", "answer": 2, "variants": ["is", "are", "was", "were"], "is_correct": False},
    {"question": "They said they {blank} football at 5 PM yesterday.", "answer": 0, "variants": ["were playing", "played", "play", "are playing"], "is_correct": False},
    {"question": "She told me she {blank} the movie already.", "answer": 3, "variants": ["sees", "saw", "has seen", "had seen"], "is_correct": False},
    {"question": "He asked if I {blank} any help.", "answer": 1, "variants": ["need", "needed", "will need", "needing"], "is_correct": False},
    {"question": "She said she {blank} busy that day.", "answer": 2, "variants": ["is", "will be", "was", "be"], "is_correct": False},
    {"question": "He asked me {blank} I had seen his keys.", "answer": 0, "variants": ["if", "that", "what", "which"], "is_correct": False},
    {"question": "They said they {blank} coming to the party.", "answer": 1, "variants": ["are", "were", "will be", "be"], "is_correct": False},

    # COMPARATIVES & SUPERLATIVES (20)
    {"question": "This car is {blank} than that one.", "answer": 1, "variants": ["fast", "faster", "fastest", "more fast"], "is_correct": False},
    {"question": "Mount Everest is the {blank} mountain in the world.", "answer": 2, "variants": ["high", "higher", "highest", "most high"], "is_correct": False},
    {"question": "She is the {blank} person I know.", "answer": 3, "variants": ["intelligent", "more intelligent", "most intelligentest", "most intelligent"], "is_correct": False},
    {"question": "Learning English is {blank} than learning Chinese.", "answer": 0, "variants": ["easier", "easiest", "more easy", "easy"], "is_correct": False},
    {"question": "This is the {blank} day of my life.", "answer": 1, "variants": ["good", "best", "better", "well"], "is_correct": False},
    {"question": "He is {blank} at math than his sister.", "answer": 2, "variants": ["bad", "badder", "worse", "worst"], "is_correct": False},
    {"question": "Tokyo is one of the {blank} cities in the world.", "answer": 3, "variants": ["busy", "busier", "most busy", "busiest"], "is_correct": False},
    {"question": "Gold is {blank} than silver.", "answer": 0, "variants": ["more expensive", "expensive", "expensiver", "most expensive"], "is_correct": False},
    {"question": "She is not as {blank} as her brother.", "answer": 1, "variants": ["taller", "tall", "tallest", "more tall"], "is_correct": False},
    {"question": "That was the {blank} movie I've ever seen.", "answer": 2, "variants": ["bore", "boring", "most boring", "more boring"], "is_correct": False},
    {"question": "The weather today is {blank} than yesterday.", "answer": 0, "variants": ["better", "best", "good", "well"], "is_correct": False},
    {"question": "He runs {blank} than I do.", "answer": 1, "variants": ["fast", "faster", "fastest", "more fast"], "is_correct": False},
    {"question": "This is the {blank} expensive watch in the shop.", "answer": 2, "variants": ["more", "mostest", "least", "lesser"], "is_correct": False},
    {"question": "She is {blank} than her cousin.", "answer": 3, "variants": ["pretty", "prettier", "prettiest", "more pretty"], "is_correct": False},
    {"question": "My house is {blank} from the city than yours.", "answer": 0, "variants": ["further", "far", "farthest", "more far"], "is_correct": False},
    {"question": "It's {blank} today than it was yesterday.", "answer": 1, "variants": ["hot", "hotter", "hottest", "more hot"], "is_correct": False},
    {"question": "This is the {blank} book I have ever read.", "answer": 2, "variants": ["interesting", "more interesting", "most interesting", "interestingest"], "is_correct": False},
    {"question": "The task was {blank} than I expected.", "answer": 3, "variants": ["hard", "harder", "hardest", "more hard"], "is_correct": False},
    {"question": "He is the {blank} member of the family.", "answer": 0, "variants": ["youngest", "younger", "young", "most young"], "is_correct": False},
    {"question": "Health is {blank} than wealth.", "answer": 1, "variants": ["important", "more important", "most important", "importanter"], "is_correct": False},

    # ADVANCED TENSES (20)
    {"question": "By the time we arrive, the movie {blank}.", "answer": 1, "variants": ["will start", "will have started", "starts", "started"], "is_correct": False},
    {"question": "I {blank} my keys; have you seen them?", "answer": 2, "variants": ["lost", "lose", "have lost", "am losing"], "is_correct": False},
    {"question": "She {blank} in this house for ten years now.", "answer": 3, "variants": ["lives", "lived", "is living", "has lived"], "is_correct": False},
    {"question": "We {blank} our dinner when the doorbell rang.", "answer": 0, "variants": ["were having", "had", "have", "are having"], "is_correct": False},
    {"question": "I {blank} to Paris twice already.", "answer": 1, "variants": ["was", "have been", "am", "went"], "is_correct": False},
    {"question": "By 2030, scientists {blank} a cure for many diseases.", "answer": 2, "variants": ["discover", "will discover", "will have discovered", "discovered"], "is_correct": False},
    {"question": "He {blank} TV for three hours before he went to bed.", "answer": 3, "variants": ["watches", "is watching", "has watched", "had been watching"], "is_correct": False},
    {"question": "I {blank} you as soon as I get home.", "answer": 0, "variants": ["will call", "call", "called", "would call"], "is_correct": False},
    {"question": "They {blank} each other since they were children.", "answer": 1, "variants": ["know", "have known", "knew", "are knowing"], "is_correct": False},
    {"question": "The sun {blank} in the east.", "answer": 2, "variants": ["rise", "rose", "rises", "rising"], "is_correct": False},
    {"question": "I {blank} my homework right now.", "answer": 3, "variants": ["do", "did", "have done", "am doing"], "is_correct": False},
    {"question": "She {blank} to the gym every morning.", "answer": 0, "variants": ["goes", "go", "is going", "went"], "is_correct": False},
    {"question": "By the time he was twenty, he {blank} three books.", "answer": 1, "variants": ["writes", "had written", "wrote", "was writing"], "is_correct": False},
    {"question": "We {blank} waiting for you for over an hour!", "answer": 2, "variants": ["were", "are", "have been", "had"], "is_correct": False},
    {"question": "I {blank} a sandwich when I saw the accident.", "answer": 3, "variants": ["eat", "ate", "have eaten", "was eating"], "is_correct": False},
    {"question": "He {blank} his work by 5 PM tomorrow.", "answer": 0, "variants": ["will have finished", "finishes", "finished", "is finishing"], "is_correct": False},
    {"question": "I {blank} to the radio while I was driving.", "answer": 1, "variants": ["listen", "was listening", "listened", "have listened"], "is_correct": False},
    {"question": "They {blank} football in the park at the moment.", "answer": 2, "variants": ["play", "played", "are playing", "have played"], "is_correct": False},
    {"question": "I {blank} him since last year.", "answer": 3, "variants": ["didn't see", "not see", "don't see", "haven't seen"], "is_correct": False},
    {"question": "She {blank} very hard lately.", "answer": 0, "variants": ["has been working", "works", "worked", "is working"], "is_correct": False},

    # VOCABULARY & COLLOCATIONS (20)
    {"question": "Could you {blank} me a favor?", "answer": 0, "variants": ["do", "make", "give", "get"], "is_correct": False},
    {"question": "He made a {blank} to study harder.", "answer": 1, "variants": ["decide", "decision", "decisive", "deciding"], "is_correct": False},
    {"question": "I need to {blank} an appointment with the doctor.", "answer": 2, "variants": ["do", "get", "make", "take"], "is_correct": False},
    {"question": "Can you {blank} an eye on my bag for a minute?", "answer": 3, "variants": ["take", "give", "make", "keep"], "is_correct": False},
    {"question": "She took {blank} in the marathon.", "answer": 0, "variants": ["part", "place", "role", "action"], "is_correct": False},
    {"question": "We need to {blank} a solution to this problem.", "answer": 1, "variants": ["make", "find", "do", "get"], "is_correct": False},
    {"question": "He has a very {blank} imagination.", "answer": 2, "variants": ["large", "big", "vivid", "high"], "is_correct": False},
    {"question": "I'm sorry, I {blank} a mistake.", "answer": 3, "variants": ["did", "got", "took", "made"], "is_correct": False},
    {"question": "Can you {blank} the difference between these two?", "answer": 0, "variants": ["tell", "say", "speak", "talk"], "is_correct": False},
    {"question": "He {blank} a lot of money last year.", "answer": 1, "variants": ["won", "earned", "gained", "took"], "is_correct": False},
    {"question": "I {blank} progress in my English studies.", "answer": 2, "variants": ["did", "got", "made", "took"], "is_correct": False},
    {"question": "She {blank} her best to help us.", "answer": 0, "variants": ["did", "made", "gave", "took"], "is_correct": False},
    {"question": "We should {blank} a look at the map.", "answer": 1, "variants": ["do", "take", "make", "get"], "is_correct": False},
    {"question": "He {blank} a speech at the wedding.", "answer": 2, "variants": ["did", "made", "gave", "took"], "is_correct": False},
    {"question": "Can you {blank} a secret?", "answer": 3, "variants": ["hold", "stay", "get", "keep"], "is_correct": False},
    {"question": "The plane {blank} off on time.", "answer": 0, "variants": ["took", "made", "got", "did"], "is_correct": False},
    {"question": "He {blank} a complaint about the service.", "answer": 1, "variants": ["did", "made", "took", "gave"], "is_correct": False},
    {"question": "She {blank} care of her younger brother.", "answer": 2, "variants": ["makes", "does", "takes", "gets"], "is_correct": False},
    {"question": "I need to {blank} some shopping.", "answer": 0, "variants": ["do", "make", "get", "take"], "is_correct": False},
    {"question": "They {blank} fun of his new haircut.", "answer": 1, "variants": ["did", "made", "took", "gave"], "is_correct": False},

    # PRONOUNS & QUANTIFIERS (20)
    {"question": "Is there {blank} milk in the fridge?", "answer": 0, "variants": ["any", "some", "many", "few"], "is_correct": False},
    {"question": "I have {blank} books on my shelf.", "answer": 1, "variants": ["much", "a few", "a little", "any"], "is_correct": False},
    {"question": "He doesn't have {blank} friends.", "answer": 2, "variants": ["much", "some", "many", "little"], "is_correct": False},
    {"question": "Can I have {blank} water?", "answer": 3, "variants": ["any", "many", "few", "some"], "is_correct": False},
    {"question": "I saw {blank} at the park.", "answer": 0, "variants": ["somebody", "anybody", "nobody", "everybody"], "is_correct": False},
    {"question": "Is {blank} ready for the test?", "answer": 1, "variants": ["someone", "everyone", "anyone", "no one"], "is_correct": False},
    {"question": "I don't know {blank} about this.", "answer": 2, "variants": ["something", "nothing", "anything", "everything"], "is_correct": False},
    {"question": "There is {blank} in the box; it's empty.", "answer": 3, "variants": ["something", "anything", "everything", "nothing"], "is_correct": False},
    {"question": "Does {blank} have a pen I can borrow?", "answer": 2, "variants": ["someone", "everyone", "anyone", "no one"], "is_correct": False},
    {"question": "I have {blank} time to finish this.", "answer": 1, "variants": ["much", "little", "few", "many"], "is_correct": False},
    {"question": "How {blank} money do you have?", "answer": 0, "variants": ["much", "many", "few", "little"], "is_correct": False},
    {"question": "There are {blank} people waiting outside.", "answer": 1, "variants": ["much", "several", "little", "any"], "is_correct": False},
    {"question": "I don't like {blank} of these movies.", "answer": 2, "variants": ["both", "neither", "either", "each"], "is_correct": False},
    {"question": "Neither of my brothers {blank} here.", "answer": 1, "variants": ["are", "is", "were", "be"], "is_correct": False},
    {"question": "Both of the girls {blank} very smart.", "answer": 0, "variants": ["are", "is", "was", "be"], "is_correct": False},
    {"question": "Each of the children {blank} an ice cream.", "answer": 1, "variants": ["have", "has", "are having", "were having"], "is_correct": False},
    {"question": "All of the water {blank} spilled.", "answer": 1, "variants": ["were", "was", "are", "be"], "is_correct": False},
    {"question": "None of the information {blank} correct.", "answer": 1, "variants": ["are", "is", "were", "be"], "is_correct": False},
    {"question": "He has {blank} knowledge of the subject.", "answer": 0, "variants": ["little", "few", "many", "much"], "is_correct": False},
    {"question": "I have {blank} more questions to ask.", "answer": 1, "variants": ["any", "a few", "much", "a little"], "is_correct": False},
    # IDIOMS & EXPRESSIONS (20)
    {"question": "That math exam was a {blank} of cake.", "answer": 1, "variants": ["slice", "piece", "portion", "bit"], "is_correct": False},
    {"question": "I'm feeling a bit under the {blank} today.", "answer": 2, "variants": ["rain", "cloud", "weather", "storm"], "is_correct": False},
    {"question": "You should break a {blank} during your performance!", "answer": 3, "variants": ["arm", "hand", "finger", "leg"], "is_correct": False},
    {"question": "Let's call it a {blank}; we've worked enough.", "answer": 0, "variants": ["day", "night", "time", "week"], "is_correct": False},
    {"question": "He's always pulling my {blank} with his jokes.", "answer": 1, "variants": ["arm", "leg", "ear", "hair"], "is_correct": False},
    {"question": "The news came out of the {blank}.", "answer": 2, "variants": ["sky", "clouds", "blue", "dark"], "is_correct": False},
    {"question": "She has a heart of {blank}.", "answer": 3, "variants": ["silver", "stone", "iron", "gold"], "is_correct": False},
    {"question": "I'm all {blank}; please tell me the secret.", "answer": 0, "variants": ["ears", "eyes", "mouth", "hands"], "is_correct": False},
    {"question": "Don't beat around the {blank}; just say it.", "answer": 1, "variants": ["tree", "bush", "corner", "wall"], "is_correct": False},
    {"question": "We're in the same {blank}, so let's cooperate.", "answer": 2, "variants": ["car", "ship", "boat", "train"], "is_correct": False},
    {"question": "I'll keep my fingers {blank} for your success.", "answer": 3, "variants": ["tied", "locked", "held", "crossed"], "is_correct": False},
    {"question": "It's time to face the {blank}.", "answer": 0, "variants": ["music", "truth", "facts", "crowd"], "is_correct": False},
    {"question": "She hit the {blank} on the head with that idea.", "answer": 1, "variants": ["hammer", "nail", "screw", "pin"], "is_correct": False},
    {"question": "Better late than {blank}.", "answer": 2, "variants": ["late", "delayed", "never", "sorry"], "is_correct": False},
    {"question": "That car cost an arm and a {blank}.", "answer": 3, "variants": ["foot", "hand", "shoulder", "leg"], "is_correct": False},
    {"question": "He has a {blank} tooth and loves chocolate.", "answer": 0, "variants": ["sweet", "sugar", "candy", "honey"], "is_correct": False},
    {"question": "Let's get the show on the {blank}.", "answer": 1, "variants": ["path", "road", "track", "way"], "is_correct": False},
    {"question": "I'm over the {blank} about my promotion!", "answer": 2, "variants": ["sun", "stars", "moon", "world"], "is_correct": False},
    {"question": "The ball is in your {blank} now.", "answer": 3, "variants": ["hands", "field", "side", "court"], "is_correct": False},
    {"question": "Take it with a grain of {blank}.", "answer": 0, "variants": ["salt", "pepper", "sugar", "sand"], "is_correct": False},

    # BUSINESS & FORMAL ENGLISH (20)
    {"question": "We need to {blank} the meeting until next Friday.", "answer": 1, "variants": ["cancel", "postpone", "reject", "deny"], "is_correct": False},
    {"question": "Please find the requested file {blank} to this email.", "answer": 2, "variants": ["included", "joined", "attached", "connected"], "is_correct": False},
    {"question": "The company's annual {blank} report is due soon.", "answer": 3, "variants": ["money", "cash", "bank", "financial"], "is_correct": False},
    {"question": "We are looking for a {blank} candidate for the position.", "answer": 0, "variants": ["suitable", "goodish", "nice", "proper"], "is_correct": False},
    {"question": "I would like to {blank} for the post of manager.", "answer": 1, "variants": ["ask", "apply", "request", "seek"], "is_correct": False},
    {"question": "The CEO will {blank} a statement later today.", "answer": 2, "variants": ["make", "do", "issue", "say"], "is_correct": False},
    {"question": "We must {blank} our costs to stay competitive.", "answer": 3, "variants": ["low", "shorten", "shrink", "reduce"], "is_correct": False},
    {"question": "I am writing to {blank} receipt of your letter.", "answer": 0, "variants": ["acknowledge", "know", "see", "accept"], "is_correct": False},
    {"question": "The merger will {blank} in significant growth.", "answer": 1, "variants": ["cause", "result", "lead", "make"], "is_correct": False},
    {"question": "She has been promoted to a senior {blank}.", "answer": 2, "variants": ["job", "work", "position", "place"], "is_correct": False},
    {"question": "Can we {blank} on a date for the presentation?", "answer": 3, "variants": ["say", "tell", "think", "agree"], "is_correct": False},
    {"question": "We aim to {blank} our customers' expectations.", "answer": 0, "variants": ["exceed", "pass", "top", "win"], "is_correct": False},
    {"question": "The project is currently {blank} schedule.", "answer": 1, "variants": ["in", "behind", "after", "slow"], "is_correct": False},
    {"question": "I'm afraid I have a prior {blank}.", "answer": 2, "variants": ["meeting", "work", "commitment", "job"], "is_correct": False},
    {"question": "Please {blank} me if you require further information.", "answer": 3, "variants": ["call", "tell", "ask", "contact"], "is_correct": False},
    {"question": "We are {blank} to launch the new product in May.", "answer": 0, "variants": ["scheduled", "timed", "setted", "fixed"], "is_correct": False},
    {"question": "Your feedback is highly {blank}.", "answer": 1, "variants": ["liked", "valued", "wanted", "needed"], "is_correct": False},
    {"question": "The budget was {blank} by the board of directors.", "answer": 2, "variants": ["seen", "done", "approved", "given"], "is_correct": False},
    {"question": "Let's {blank} the main points of the discussion.", "answer": 3, "variants": ["repeat", "shorten", "fix", "summarize"], "is_correct": False},
    {"question": "We are experiencing technical {blank}.", "answer": 0, "variants": ["difficulties", "bads", "errors", "breaks"], "is_correct": False},

    # ADVANCED PREPOSITIONS & PHRASES (20)
    {"question": "He succeeded {blank} passing the exam.", "answer": 1, "variants": ["on", "in", "at", "to"], "is_correct": False},
    {"question": "She apologized {blank} being late.", "answer": 2, "variants": ["of", "to", "for", "with"], "is_correct": False},
    {"question": "I am fed up {blank} this cold weather.", "answer": 3, "variants": ["of", "for", "by", "with"], "is_correct": False},
    {"question": "The solution {blank} the problem was simple.", "answer": 0, "variants": ["to", "of", "for", "in"], "is_correct": False},
    {"question": "He is very similar {blank} his father.", "answer": 1, "variants": ["with", "to", "as", "like"], "is_correct": False},
    {"question": "I'm not used {blank} getting up so early.", "answer": 2, "variants": ["for", "at", "to", "with"], "is_correct": False},
    {"question": "She insisted {blank} paying for the dinner.", "answer": 3, "variants": ["for", "to", "at", "on"], "is_correct": False},
    {"question": "He is capable {blank} doing much better.", "answer": 0, "variants": ["of", "for", "in", "to"], "is_correct": False},
    {"question": "I'm worried {blank} my upcoming interview.", "answer": 1, "variants": ["for", "about", "of", "with"], "is_correct": False},
    {"question": "They arrived {blank} the airport just in time.", "answer": 2, "variants": ["to", "in", "at", "on"], "is_correct": False},
    {"question": "I'm envious {blank} your new house.", "answer": 3, "variants": ["for", "with", "about", "of"], "is_correct": False},
    {"question": "He is addicted {blank} video games.", "answer": 0, "variants": ["to", "on", "for", "with"], "is_correct": False},
    {"question": "She is famous {blank} her beautiful paintings.", "answer": 1, "variants": ["by", "for", "of", "with"], "is_correct": False},
    {"question": "I'm responsible {blank} the sales department.", "answer": 2, "variants": ["of", "with", "for", "to"], "is_correct": False},
    {"question": "Are you acquainted {blank} the new rules?", "answer": 3, "variants": ["of", "to", "for", "with"], "is_correct": False},
    {"question": "He is ashamed {blank} his behavior.", "answer": 0, "variants": ["of", "with", "for", "by"], "is_correct": False},
    {"question": "We are dependent {blank} the weather.", "answer": 1, "variants": ["of", "on", "to", "with"], "is_correct": False},
    {"question": "I'm grateful {blank} your help.", "answer": 2, "variants": ["to", "with", "for", "of"], "is_correct": False},
    {"question": "She is tired {blank} doing the same thing.", "answer": 3, "variants": ["with", "for", "by", "of"], "is_correct": False},
    {"question": "He is allergic {blank} cats.", "answer": 0, "variants": ["to", "for", "with", "of"], "is_correct": False},

    # WORD FORMATION (20)
    {"question": "The {blank} of the bridge took two years.", "answer": 1, "variants": ["construct", "construction", "constructive", "constructor"], "is_correct": False},
    {"question": "She is very {blank} and loves painting.", "answer": 2, "variants": ["create", "creation", "creative", "creatively"], "is_correct": False},
    {"question": "I can't believe his {blank}!", "answer": 3, "variants": ["stupid", "stupidity", "stupidly", "stupider"], "is_correct": False},
    {"question": "The weather is very {blank} today.", "answer": 0, "variants": ["unpredictable", "predict", "prediction", "predictive"], "is_correct": False},
    {"question": "He works as a professional {blank}.", "answer": 1, "variants": ["photograph", "photographer", "photographic", "photography"], "is_correct": False},
    {"question": "The {blank} was a huge success.", "answer": 2, "variants": ["perform", "performed", "performance", "performer"], "is_correct": False},
    {"question": "We need to find a {blank} to this problem.", "answer": 3, "variants": ["solve", "solved", "solvable", "solution"], "is_correct": False},
    {"question": "It was very {blank} of you to help.", "answer": 0, "variants": ["thoughtful", "thought", "think", "thoughtless"], "is_correct": False},
    {"question": "The {blank} of the planet is critical.", "answer": 1, "variants": ["protect", "protection", "protective", "protector"], "is_correct": False},
    {"question": "He showed great {blank} during the crisis.", "answer": 2, "variants": ["courage", "courageous", "bravery", "brave"], "is_correct": False},
    {"question": "The child's {blank} was excellent.", "answer": 3, "variants": ["behave", "behaved", "behavioral", "behavior"], "is_correct": False},
    {"question": "She is a very {blank} person.", "answer": 0, "variants": ["knowledgeable", "knowledge", "know", "knowing"], "is_correct": False},
    {"question": "The {blank} between the two is obvious.", "answer": 1, "variants": ["differ", "difference", "different", "differently"], "is_correct": False},
    {"question": "We enjoyed the {blank} of the park.", "answer": 2, "variants": ["beautiful", "beautify", "beauty", "beautifully"], "is_correct": False},
    {"question": "His {blank} to leave surprised everyone.", "answer": 3, "variants": ["decide", "deciding", "decisive", "decision"], "is_correct": False},
    {"question": "The movie was very {blank}.", "answer": 0, "variants": ["enjoyable", "enjoy", "enjoyed", "enjoyment"], "is_correct": False},
    {"question": "We need to {blank} the situation.", "answer": 1, "variants": ["analysis", "analyze", "analytical", "analyst"], "is_correct": False},
    {"question": "Her {blank} as a dancer is well-known.", "answer": 2, "variants": ["able", "ably", "ability", "abled"], "is_correct": False},
    {"question": "The news was quite {blank}.", "answer": 3, "variants": ["shock", "shocked", "shockingly", "shocking"], "is_correct": False},
    {"question": "I have a lot of {blank} for him.", "answer": 0, "variants": ["admiration", "admire", "admired", "admiring"], "is_correct": False},

    # PHRASAL VERBS SET 2 (20)
    {"question": "The car {blank} on the highway.", "answer": 1, "variants": ["broke up", "broke down", "broke into", "broke out"], "is_correct": False},
    {"question": "I need to {blank} on my sleep.", "answer": 2, "variants": ["catch up", "catch in", "catch out", "catch with"], "is_correct": False},
    {"question": "She {blank} the job offer.", "answer": 3, "variants": ["turned on", "turned up", "turned in", "turned down"], "is_correct": False},
    {"question": "We {blank} of gas in the middle of nowhere.", "answer": 0, "variants": ["ran out", "ran into", "ran away", "ran over"], "is_correct": False},
    {"question": "I {blank} my old teacher yesterday.", "answer": 1, "variants": ["ran into", "ran after", "ran for", "ran up"], "is_correct": False},
    {"question": "Can you {blank} the music? It's too loud.", "answer": 2, "variants": ["turn up", "turn on", "turn down", "turn off"], "is_correct": False},
    {"question": "He decided to {blank} smoking.", "answer": 3, "variants": ["give in", "give out", "give away", "give up"], "is_correct": False},
    {"question": "I'll {blank} you at 8 PM.", "answer": 0, "variants": ["pick up", "pick in", "pick out", "pick off"], "is_correct": False},
    {"question": "Don't {blank} the truth from me.", "answer": 1, "variants": ["hold on", "hold back", "hold up", "hold in"], "is_correct": False},
    {"question": "We need to {blank} the details of the plan.", "answer": 2, "variants": ["work in", "work on", "work out", "work for"], "is_correct": False},
    {"question": "The plane {blank} an hour late.", "answer": 3, "variants": ["took in", "took up", "took on", "took off"], "is_correct": False},
    {"question": "I {blank} an interesting fact today.", "answer": 0, "variants": ["came across", "came into", "came by", "came up"], "is_correct": False},
    {"question": "She {blank} her mother.", "answer": 1, "variants": ["takes off", "takes after", "takes up", "takes in"], "is_correct": False},
    {"question": "Let's {blank} the meeting.", "answer": 2, "variants": ["go on", "go in", "go ahead with", "go up"], "is_correct": False},
    {"question": "He {blank} a great idea for the project.", "answer": 3, "variants": ["came with", "came to", "came for", "came up with"], "is_correct": False},
    {"question": "I have to {blank} my little sister tonight.", "answer": 0, "variants": ["look after", "look at", "look for", "look into"], "is_correct": False},
    {"question": "The bomb {blank} in the city center.", "answer": 1, "variants": ["went in", "went off", "went up", "went on"], "is_correct": False},
    {"question": "She {blank} with her boyfriend last week.", "answer": 2, "variants": ["broke down", "broke in", "broke up", "broke out"], "is_correct": False},
    {"question": "I'll {blank} the word in the dictionary.", "answer": 3, "variants": ["look at", "look after", "look for", "look up"], "is_correct": False},
    {"question": "The fire {blank} in the kitchen.", "answer": 1, "variants": ["broke up", "broke out", "broke into", "broke down"], "is_correct": False},

    # QUESTION TAGS (10)
    {"question": "You're coming to the party, {blank}?", "answer": 1, "variants": ["are you", "aren't you", "don't you", "do you"], "is_correct": False},
    {"question": "He lives in London, {blank}?", "answer": 2, "variants": ["isn't he", "doesn't he", "does he", "is he"], "is_correct": False},
    {"question": "They haven't seen the movie, {blank}?", "answer": 3, "variants": ["haven't they", "aren't they", "do they", "have they"], "is_correct": False},
    {"question": "I'm right, {blank}?", "answer": 0, "variants": ["aren't I", "am I not", "don't I", "am I"], "is_correct": False},
    {"question": "Let's go for a walk, {blank}?", "answer": 1, "variants": ["shall we", "won't we", "will we", "don't we"], "is_correct": False},
    {"question": "She can swim, {blank}?", "answer": 2, "variants": ["can she", "doesn't she", "can't she", "is she"], "is_correct": False},
    {"question": "You won't forget, {blank}?", "answer": 3, "variants": ["don't you", "will not you", "won't you", "will you"], "is_correct": False},
    {"question": "There is a meeting today, {blank}?", "answer": 0, "variants": ["isn't there", "is there", "doesn't there", "don't there"], "is_correct": False},
    {"question": "He has a car, {blank}?", "answer": 1, "variants": ["has he", "doesn't he", "isn't he", "hasn't he"], "is_correct": False},
    {"question": "Don't be late, {blank}?", "answer": 2, "variants": ["do you", "don't you", "will you", "shall you"], "is_correct": False},

    # SUBJUNCTIVE MOOD (10)
    {"question": "I suggest that he {blank} more regularly.", "answer": 1, "variants": ["exercises", "exercise", "exercised", "exercising"], "is_correct": False},
    {"question": "It is essential that she {blank} here on time.", "answer": 2, "variants": ["is", "was", "be", "been"], "is_correct": False},
    {"question": "I wish I {blank} taller.", "answer": 3, "variants": ["am", "is", "was", "were"], "is_correct": False},
    {"question": "If I {blank} you, I wouldn't do that.", "answer": 0, "variants": ["were", "was", "am", "be"], "is_correct": False},
    {"question": "She requested that the meeting {blank} postponed.", "answer": 1, "variants": ["is", "be", "was", "been"], "is_correct": False},
    {"question": "It is important that he {blank} the truth.", "answer": 2, "variants": ["knows", "knew", "know", "known"], "is_correct": False},
    {"question": "I recommend that you {blank} the job.", "answer": 3, "variants": ["takes", "took", "taking", "take"], "is_correct": False},
    {"question": "God {blank} the Queen.", "answer": 0, "variants": ["save", "saves", "saved", "saving"], "is_correct": False},
    {"question": "I would rather you {blank} stay tonight.", "answer": 1, "variants": ["don't", "didn't", "not", "haven't"], "is_correct": False},
    {"question": "It's high time we {blank} home.", "answer": 2, "variants": ["go", "are going", "went", "have gone"], "is_correct": False},

    # CAUSATIVE VERBS (10)
    {"question": "I had the mechanic {blank} my car.", "answer": 1, "variants": ["repaired", "repair", "to repair", "repairing"], "is_correct": False},
    {"question": "She got her hair {blank} yesterday.", "answer": 2, "variants": ["cutted", "cutting", "cut", "to cut"], "is_correct": False},
    {"question": "I'll have my assistant {blank} you the files.", "answer": 3, "variants": ["sent", "to send", "sending", "send"], "is_correct": False},
    {"question": "We need to get the house {blank} before the party.", "answer": 0, "variants": ["cleaned", "clean", "to clean", "cleaning"], "is_correct": False},
    {"question": "He had his bike {blank} last week.", "answer": 1, "variants": ["steal", "stolen", "to steal", "stealing"], "is_correct": False},
    {"question": "She made him {blank} the whole room.", "answer": 2, "variants": ["cleaned", "to clean", "clean", "cleaning"], "is_correct": False},
    {"question": "I'll get the plumber {blank} the leak.", "answer": 3, "variants": ["fix", "fixed", "fixing", "to fix"], "is_correct": False},
    {"question": "We had the windows {blank} last month.", "answer": 0, "variants": ["replaced", "replace", "to replace", "replacing"], "is_correct": False},
    {"question": "He let the children {blank} in the garden.", "answer": 1, "variants": ["played", "play", "to play", "playing"], "is_correct": False},
    {"question": "I'll have the package {blank} to your office.", "answer": 2, "variants": ["deliver", "delivering", "delivered", "to deliver"], "is_correct": False},

    # INVERSION (10)
    {"question": "Never {blank} I seen such a beautiful sunset.", "answer": 1, "variants": ["I have", "have I", "did I", "I had"], "is_correct": False},
    {"question": "Hardly {blank} I started when it began to rain.", "answer": 2, "variants": ["I had", "did I", "had I", "I have"], "is_correct": False},
    {"question": "Rarely {blank} he go out late at night.", "answer": 3, "variants": ["he does", "is he", "does he", "do he"], "is_correct": False},
    {"question": "Only then {blank} I realize my mistake.", "answer": 0, "variants": ["did I", "I did", "I had", "had I"], "is_correct": False},
    {"question": "Seldom {blank} we see such talent.", "answer": 1, "variants": ["we do", "do we", "are we", "did we"], "is_correct": False},
    {"question": "Under no circumstances {blank} you leave the room.", "answer": 2, "variants": ["you should", "should you", "you must", "must you"], "is_correct": False},
    {"question": "Little {blank} she know about the surprise.", "answer": 3, "variants": ["she did", "did she", "she does", "does she"], "is_correct": False},
    {"question": "Not only {blank} he smart, but he is also kind.", "answer": 0, "variants": ["is he", "he is", "does he", "he does"], "is_correct": False},
    {"question": "No sooner {blank} she arrived than the phone rang.", "answer": 1, "variants": ["she had", "had she", "did she", "she did"], "is_correct": False},
    {"question": "At no time {blank} he mention the secret.", "answer": 2, "variants": ["he did", "did he", "he does", "does he"], "is_correct": False},

    # DETERMINERS & ARTICLES (20)
    {"question": "I like {blank} cats.", "answer": 1, "variants": ["the", "none (zero article)", "a", "an"], "is_correct": False},
    {"question": "She goes to {blank} church every Sunday.", "answer": 2, "variants": ["the", "a", "none (zero article)", "some"], "is_correct": False},
    {"question": "He is {blank} honest man.", "answer": 3, "variants": ["a", "the", "some", "an"], "is_correct": False},
    {"question": "We went to {blank} Philippines last year.", "answer": 0, "variants": ["the", "a", "an", "none"], "is_correct": False},
    {"question": "I have {blank} idea.", "answer": 1, "variants": ["a", "an", "the", "some"], "is_correct": False},
    {"question": "She plays {blank} piano beautifully.", "answer": 2, "variants": ["a", "an", "the", "none"], "is_correct": False},
    {"question": "Mount Everest is in {blank} Himalayas.", "answer": 3, "variants": ["a", "an", "none", "the"], "is_correct": False},
    {"question": "{blank} students in the class were listening.", "answer": 0, "variants": ["All", "Each", "Every", "Neither"], "is_correct": False},
    {"question": "I have {blank} friend in Paris.", "answer": 1, "variants": ["some", "a", "an", "any"], "is_correct": False},
    {"question": "She gave {blank} child a present.", "answer": 2, "variants": ["all", "none", "each", "both"], "is_correct": False},
    {"question": "I didn't like {blank} of the two choices.", "answer": 3, "variants": ["both", "all", "none", "either"], "is_correct": False},
    {"question": "There is {blank} milk left.", "answer": 0, "variants": ["no", "none", "neither", "any"], "is_correct": False},
    {"question": "He has {blank} money to buy a car.", "answer": 1, "variants": ["few", "enough", "many", "several"], "is_correct": False},
    {"question": "I have {blank} interest in politics.", "answer": 2, "variants": ["few", "many", "little", "any"], "is_correct": False},
    {"question": "She has {blank} books on her shelf.", "answer": 3, "variants": ["much", "little", "any", "several"], "is_correct": False},
    {"question": "I have {blank} to tell you.", "answer": 0, "variants": ["nothing", "anything", "everything", "something"], "is_correct": False},
    {"question": "Does {blank} have a pen?", "answer": 1, "variants": ["someone", "anyone", "everyone", "no one"], "is_correct": False},
    {"question": "I saw {blank} at the park.", "answer": 2, "variants": ["anybody", "nobody", "somebody", "everybody"], "is_correct": False},
    {"question": "Is {blank} ready?", "answer": 3, "variants": ["someone", "anyone", "no one", "everyone"], "is_correct": False},
    {"question": "I don't know {blank} about this.", "answer": 2, "variants": ["something", "nothing", "anything", "everything"], "is_correct": False},

    # MIXED ADVANCED REVIEW (40)
    {"question": "I wish I {blank} more time to finish.", "answer": 1, "variants": ["have", "had", "will have", "am having"], "is_correct": False},
    {"question": "She would have come if she {blank}.", "answer": 2, "variants": ["knows", "knew", "had known", "has known"], "is_correct": False},
    {"question": "The man {blank} is standing there is my brother.", "answer": 3, "variants": ["which", "whom", "whose", "who"], "is_correct": False},
    {"question": "By next year, I {blank} here for ten years.", "answer": 0, "variants": ["will have lived", "will live", "live", "am living"], "is_correct": False},
    {"question": "He {blank} TV when I arrived.", "answer": 1, "variants": ["watches", "was watching", "is watching", "watched"], "is_correct": False},
    {"question": "I am looking forward {blank} you.", "answer": 2, "variants": ["to see", "see", "to seeing", "seeing"], "is_correct": False},
    {"question": "She is used to {blank} early.", "answer": 3, "variants": ["get up", "got up", "to get up", "getting up"], "is_correct": False},
    {"question": "The bridge {blank} two years ago.", "answer": 0, "variants": ["was built", "built", "is built", "was building"], "is_correct": False},
    {"question": "He {blank} speak three languages.", "answer": 1, "variants": ["could", "can", "may", "might"], "is_correct": False},
    {"question": "I suggest that she {blank} hard.", "answer": 2, "variants": ["studies", "studied", "study", "studying"], "is_correct": False},
    {"question": "It's {blank} movie I've ever seen.", "answer": 3, "variants": ["best", "better", "good", "the best"], "is_correct": False},
    {"question": "I {blank} rather stay at home.", "answer": 0, "variants": ["would", "should", "could", "had"], "is_correct": False},
    {"question": "She {blank} her lunch at the moment.", "answer": 1, "variants": ["eat", "is eating", "eats", "ate"], "is_correct": False},
    {"question": "If it {blank} tomorrow, we'll go.", "answer": 2, "variants": ["rain", "rained", "rains", "will rain"], "is_correct": False},
    {"question": "He {blank} to the gym every day.", "answer": 3, "variants": ["go", "is going", "went", "goes"], "is_correct": False},
    {"question": "I have {blank} friends in this city.", "answer": 0, "variants": ["few", "a little", "any", "much"], "is_correct": False},
    {"question": "The car {blank} down on the way.", "answer": 1, "variants": ["broke up", "broke down", "broke into", "broke out"], "is_correct": False},
    {"question": "She told me she {blank} tired.", "answer": 2, "variants": ["is", "will be", "was", "be"], "is_correct": False},
    {"question": "I'll {blank} you up at 7 PM.", "answer": 3, "variants": ["get", "take", "bring", "pick"], "is_correct": False},
    {"question": "He is interested {blank} art.", "answer": 0, "variants": ["in", "on", "at", "about"], "is_correct": False},
    {"question": "We went to the store {blank} foot.", "answer": 1, "variants": ["by", "on", "with", "in"], "is_correct": False},
    {"question": "I saw {blank} amazing movie.", "answer": 2, "variants": ["a", "the", "an", "some"], "is_correct": False},
    {"question": "The keys are {blank} the table.", "answer": 3, "variants": ["in", "at", "between", "on"], "is_correct": False},
    {"question": "Wait {blank} me.", "answer": 0, "variants": ["for", "to", "at", "with"], "is_correct": False},
    {"question": "He is taller {blank} his brother.", "answer": 1, "variants": ["as", "than", "that", "from"], "is_correct": False},
    {"question": "She speaks English very {blank}.", "answer": 2, "variants": ["good", "goodly", "well", "best"], "is_correct": False},
    {"question": "I haven't seen him {blank} a long time.", "answer": 3, "variants": ["since", "during", "while", "for"], "is_correct": False},
    {"question": "The exam was {blank} easy.", "answer": 0, "variants": ["surprisingly", "surprise", "surprised", "surprising"], "is_correct": False},
    {"question": "I {blank} English for five years.", "answer": 1, "variants": ["study", "have been studying", "am studying", "studied"], "is_correct": False},
    {"question": "If I {blank} you, I would go.", "answer": 2, "variants": ["am", "was", "were", "be"], "is_correct": False},
    {"question": "The news {blank} interesting.", "answer": 3, "variants": ["are", "were", "be", "is"], "is_correct": False},
    {"question": "Everyone {blank} to be happy.", "answer": 0, "variants": ["wants", "want", "is wanting", "are wanting"], "is_correct": False},
    {"question": "He made a {blank}.", "answer": 1, "variants": ["decide", "decision", "decisive", "deciding"], "is_correct": False},
    {"question": "Can you {blank} an eye on my bag?", "answer": 2, "variants": ["make", "take", "keep", "give"], "is_correct": False},
    {"question": "The plane {blank} off on time.", "answer": 3, "variants": ["took in", "took up", "took on", "took off"], "is_correct": False},
    {"question": "I am proud {blank} you.", "answer": 0, "variants": ["of", "for", "with", "in"], "is_correct": False},
    {"question": "Would you {blank} passing the salt?", "answer": 1, "variants": ["like", "mind", "please", "want"], "is_correct": False},
    {"question": "He arrives {blank} than expected.", "answer": 2, "variants": ["early", "earliest", "earlier", "more early"], "is_correct": False},
    {"question": "The team played {blank}.", "answer": 3, "variants": ["bad", "worst", "worse", "badly"], "is_correct": False},
    {"question": "I went to bed early {blank} I was tired.", "answer": 0, "variants": ["because", "so", "but", "although"], "is_correct": False},
]